### ISSUE TITLE
Can't compile with ARC

### ISSUE THREAD

**Issue by avenantsoftware** [iospirit/HIDRemote#1]
Can't you update the code for ARC?

**Comment by felix-schwarz** [comment]
HIDRemote predates ARC and needs to compile in environments where ARC is not available.

Here's how you can turn off ARC selectively for a single file in Xcode:
http://stackoverflow.com/questions/6646052/how-can-i-disable-arc-for-a-single-file-in-a-project

**Comment by avenantsoftware** [comment]
yeah I allready discovered that, but that still leaves this compile error: https://github.com/iospirit/HIDRemote/issues/2

probably because the code was written when OS X was still 32-bit

**Comment by felix-schwarz** [comment]
Unless you've enabled -Wall (off by default), this is a warning, not an error. Please let's keep discussion of #2 to #2.
